name: connectus
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  page_transition: ^2.0.4
  carousel_slider: ^5.0.0
  flutter_form_builder: ^7.7.0
  validators: ^3.0.0
  pretty_qr_code: ^3.5.0
  flutter_barcode_scanner: ^2.0.0
  supabase_flutter: ^2.5.6
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  mysql1: ^0.20.0
  shelf: ^1.2.0
  shelf_router: ^1.1.3

flutter:
  uses-material-design: true
  assets:
    - images/

  fonts:
    - family: Iceberg
      fonts:
        - asset: fonts/Iceberg-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
